export const shangyou = [
    {
        id:1,
        index:1,
        name:'锂提取与加工',
        children:[
            {
                index:11,
                name:'赣锋锂业',
            },
            {
                index:12,
                name:'天齐锂业',
            },
            {
                index:13,
                name:'永兴材料',
            },
            {
                index:14,
                name:'雅化集团',
            },
            {
                index:15,
                name:'盛新锂能',
            },
            {
                index:16,
                name:'融捷股份',
            },
            {
                index:17,
                name:'川能动力',
            },
            {
                index:18,
                name:'江特电机',
            },
        ]
    },
    {
        id:2,
        index:2,
        name:'正极材料',
        children:[
            {
                index:20,
                name:'中国宝安',
            },
            {
                index:21,
                name:'格林美',
            },
            {
                index:22,
                name:'当升科技',
            },
            {
                index:23,
                name:'科恒股份',
            },
            {
                index:24,
                name:'厦门钨业',
            },
            {
                index:25,
                name:'湘潭电化',
            },
            {
                index:26,
                name:'富临精工',
            },
            {
                index:27,
                name:'容百科技',
            },
            {
                index:28,
                name:'丰源股份',
            },
            {
                index:29,
                name:'中伟股份',
            },
            {
                index:291,
                name:'中银绒业',
            },
        ]
    },
    {
        id:3,
        index:3,
        name:'负极材料',
        children:[
            {
                index:30,
                name:'贝特瑞',
            },
            {
                index:31,
                name:'中科电气',
            },
            {
                index:32,
                name:'杉杉股份',
            },
            {
                index:33,
                name:'璞泰来',
            },
            {
                index:34,
                name:'翔丰华',
            },
        ]
    },
    {
        id:4,
        index:4,
        name:'导电剂',
        children:[
            {
                index:40,
                name:'天奈科技',
            },
            {
                index:41,
                name:'道氏技术',
            },
            {
                index:42,
                name:'德方纳米',
            },
            {
                index:43,
                name:'斯迪克',
            },
        ]
    },
    {
        id:5,
        index:5,
        name:'粘结剂',
        children:[
            {
                index:50,
                name:'回天新材',
            },
            {
                index:51,
                name:'康达新材',
            },
            {
                index:52,
                name:'高盟新材',
            },
            {
                index:53,
                name:'天洋新材',
            },
        ]
    },
    {
        id:6,
        index:6,
        name:'分散剂',
        children:[
            {
                index:60,
                name:'新开源',
            },
            {
                index:61,
                name:'瑞丰新材',
            },
            {
                index:62,
                name:'道思股份',
            },
            {
                index:63,
                name:'天奈科技',
            },
        ]
    },
    {
        id:7,
        index:7,
        name:'隔膜',
        children:[
            {
                index:70,
                name:'中财科技',
            },
            {
                index:71,
                name:'沧州明珠',
            },
            {
                index:72,
                name:'恩捷股份',
            },
            {
                index:73,
                name:'星源材质',
            },
        ]
    },
    {
        id:8,
        index:8,
        name:'铜箔',
        children:[
            {
                index:80,
                name:'诺德股份',
            },
            {
                index:81,
                name:'嘉元科技',
            },
            {
                index:82,
                name:'中一科技',
            },
            {
                index:83,
                name:'铜冠铜箔',
            },
        ]
    },
    {
        id:9,
        index:9,
        name:'电解液',
        children:[
            {
                index:90,
                name:'天赐材料',
            },
            {
                index:91,
                name:'新宙邦',
            },
            {
                index:92,
                name:'江苏国泰',
            },
            {
                index:93,
                name:'杉杉股份',
            },
            {
                index:94,
                name:'石大胜华',
            },
        ]
    },
]

export const zhongyou = [
    {
        id:1,
        index:1,
        name:'锂电芯、电池及PACK',
        children:[
            {
                index:11,
                name:'宁德时代',
            },
            {
                index:12,
                name:'亿纬锂能',
            },
            {
                index:13,
                name:'国轩高科',
            },
            {
                index:14,
                name:'鹏辉能源',
            },
            {
                index:15,
                name:'孚能科技',
            },
            {
                index:16,
                name:'比亚迪',
            },
            {
                index:17,
                name:'LG新能源',
            },
            {
                index:18,
                name:'中航锂电',
            },
            {
                index:19,
                name:'中创新航',
            },
            {
                index:20,
                name:'欣旺达',
            },
            {
                index:21,
                name:'蜂果能源',
            },
        ]
    },
]

export const xiayou = [
    {
        id:1,
        index:1,
        name:'整车厂',
        children:[
            {
                index:11,
                name:'比亚迪',
            },
            {
                index:12,
                name:'特斯拉',
            },
            {
                index:13,
                name:'广汽集团',
            },
        ]
    },
    {
        id:2,
        index:2,
        name:'电池回收',
        children:[
            {
                index:11,
                name:'赣锋锂业',
            },
            {
                index:12,
                name:'格林美',
            },
            {
                index:13,
                name:'光华科技',
            },
            {
                index:14,
                name:'宁德时代',
            },
            {
                index:15,
                name:'天奇股份',
            },
            {
                index:16,
                name:'骆驼股份',
            },
            {
                index:17,
                name:'中伟股份',
            },
            {
                index:18,
                name:'杉杉股份',
            },
            {
                index:19,
                name:'华友钻业',
            },
            {
                index:20,
                name:'超越科枝',
            },
            {
                index:21,
                name:'迪生力',
            },
        ]
    },
]

